name: Ci CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}
    
    - name: Build and push App Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          flabioassuncao/tuegapp:latest
          flabioassuncao/tuegapp:${{ github.run_number }}

  deploy:
     needs: [build]
     name: Deploy to Fly io
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: superfly/flyctl-actions/setup-flyctl@master
       - run: flyctl deploy --remote-only -a tueg
         env:
           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
